version: '3.8'

services:
  app:
    image: cactus_project-app:stack
#    build:
#      context: .
#      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - app-uploads:/app/static/uploads

  nginx:
    image: nginx:1.27.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
      - app-uploads:/app/static/uploads:ro
    networks:
      - app-network
    depends_on:
      - app

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
#    privileged: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
      - "/dev/disk:/dev/disk:ro"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: cactus-camila-swarm

volumes:
  app-uploads: